### ISSUE TITLE
Change of Plan

### ISSUE THREAD

**Issue by ne-5437** [ne-5437/AHSS_S4#6]
Presentation Feedback: 
- Since all Sensors cannot be in one place, see that you would figure out a way to design a real application by considering a room.
- Instead of NodeMCU, use Silicon Labs Board

**Comment by ne-5437** [comment]
Any other points to be added?

**Comment by ne-5437** [comment]
Comment Here!

**Comment by Sankarpoduri** [comment]
EFM specifications do u have

**Comment by ne-5437** [comment]
Currently Sir said EFM32, didn't specify anything yet
